little fix
mate-academy/layout_catalog_grid pull request #1000
Opened 2022-10-07 10:06 UTC by andriy-shymkiv

- [DEMO LINK](https://andriy-shymkiv.github.io/layout_catalog_grid/)

2022-10-08 23:24 UTC, taraselnik approved these changes
enjoy

2022-10-08 23:24 UTC, taraselnik commented on src/styles/blocks/_catalog.scss
> +    margin-bottom: 48px;
why not 'gap' above?

2022-10-11 12:41 UTC, illiarerun requested changes

2022-10-11 12:41 UTC, illiarerun commented on src/styles/blocks/_catalog.scss
> +    margin-bottom: 48px;
agree, use gap for it
```suggestion
```

2022-10-11 12:41 UTC, illiarerun commented on src/styles/blocks/_catalog.scss
> +    width: $cardWidth;
width here is not needed it should be controlled by grid
```suggestion
```

2022-10-11 12:41 UTC, illiarerun commented on src/styles/blocks/_catalog.scss
> +  margin: 0 auto;
use grid options to center items
```suggestion
```

2022-10-11 12:41 UTC, illiarerun commented on src/styles/blocks/_catalog.scss
> +  }
There should be two columns **starting** at 488px
![image](https://user-images.githubusercontent.com/37161315/195093148-fe11a9ad-ac16-46dd-afbf-20e8fa4e3a7a.png)

2022-10-11 12:41 UTC, illiarerun commented on src/styles/blocks/_catalog.scss
> +  }
same here

2022-10-11 12:41 UTC, illiarerun commented on src/styles/blocks/_catalog.scss
> +  }
and here

2022-10-16 20:33 UTC, illiarerun approved these changes

2022-10-16 20:33 UTC, illiarerun commented on src/styles/blocks/_catalog.scss
> +    grid-template-columns: repeat(1, $cardWidth);
no neec to repeat one column
```suggestion
    grid-template-columns: $cardWidth;
```

2024-03-27 08:26 UTC, closed without merging