created catalog using grid
mate-academy/layout_catalog_grid pull request #1114
Opened 2022-11-09 16:18 UTC by vladyslav-krainyk

- [DEMO LINK](https://vladyslav-krainyk.github.io/layout_catalog_grid/)

2022-11-10 09:12 UTC, stanislav-topikha requested changes
you dont need all those changes, modify only one file:` _catalog.scss`

2022-11-12 20:42 UTC, ivanchuk-yurii requested changes

2022-11-12 20:42 UTC, ivanchuk-yurii commented on src/styles/_catalog.scss
> +$scrin-size:
```suggestion
$screen-size:
```
typo

2022-11-12 20:42 UTC, ivanchuk-yurii commented on src/styles/blocks/card.scss
> +.card {
remove this

2022-11-12 20:42 UTC, ivanchuk-yurii commented on src/styles/blocks/catalog.scss
> +.catalog {
and this

2022-11-12 20:42 UTC, ivanchuk-yurii commented on src/styles/utils/_variables.scss
> +$card-width: 200px;
this too

2022-11-12 20:42 UTC, ivanchuk-yurii commented on src/styles/_catalog.scss
> +    width: $card-width;
you don't need this since you've set width in `grid-template-columns`

2022-11-13 10:25 UTC, closed without merging