layout_catalog_grid
mate-academy/layout_catalog_grid pull request #1158
Opened 2022-11-14 13:20 UTC by oksanatytanych

- [DEMO LINK](https://oksanatytanych.github.io/layout_catalog_grid/)

2022-11-15 13:19 UTC, olena-yanovska approved these changes
Good job!

2022-11-16 08:03 UTC, valerii-derkach requested changes

2022-11-16 08:03 UTC, valerii-derkach commented on src/styles/_catalog.scss
> +  grid-template-columns: repeat(1, 200px);
DRY and create variable for card width

2022-11-16 10:52 UTC, Ihor-Karpyn approved these changes

2022-12-08 16:08 UTC, closed without merging