catalog was created and updated
mate-academy/layout_catalog_grid pull request #1167
Opened 2022-11-14 16:50 UTC by batstolya

- [DEMO LINK](https://batstolya.github.io/layout_catalog_grid/)

2022-11-15 11:55 UTC, DiDemkiv requested changes
Good job😺

2022-11-15 11:55 UTC, DiDemkiv commented on src/styles/blocks/_catalog.scss
> +  grid-template-columns: repeat(4, $width-card);
not necessary to add it
```suggestion
```

2022-11-15 11:55 UTC, DiDemkiv commented on src/styles/blocks/_catalog.scss
> +  justify-items: center;
not necessary to add it
```suggestion
```

2022-11-15 11:55 UTC, DiDemkiv commented on src/styles/blocks/_catalog.scss
> +  @media (min-width: 1200px) {
There should be four columns starting at 1024px
```suggestion
  @media (min-width: 1024px) {
```

2022-11-15 11:55 UTC, DiDemkiv commented on src/styles/blocks/_catalog.scss
> +    align-items: center;
optionally you can add "place-items: center;" instead :)
```suggestion
   place-items: center;
```

2022-11-15 12:36 UTC, DiDemkiv approved these changes

2022-11-15 13:43 UTC, valerii-derkach requested changes

2022-11-15 13:43 UTC, valerii-derkach commented on src/styles/blocks/_catalog.scss
> +  }
set this property as default, no need @media here

2022-11-16 07:49 UTC, valerii-derkach approved these changes

2026-07-13 23:08 UTC, closed without merging