Catalog-grid
mate-academy/layout_catalog_grid pull request #1235
Opened 2022-12-02 15:17 UTC by mdm-21

- [DEMO LINK](https://mdm-21.github.io/layout_catalog_grid/)

2022-12-03 09:49 UTC, AlisaVlasova requested changes
let`s center cards for all screens
<img width="675" alt="image" src="https://user-images.githubusercontent.com/66749919/205434790-875eb540-a422-4401-af03-4f7bf54c1baa.png">

2022-12-03 09:49 UTC, AlisaVlasova commented on src/styles/main.scss
> +}
move it into catalog block

2022-12-04 14:39 UTC, ivanchuk-yurii requested changes

2022-12-04 14:39 UTC, ivanchuk-yurii commented on src/styles/_catalog.scss
> +    grid-template-columns: repeat(2, 200px);
```suggestion
    grid-template-columns: repeat(2, 1fr);
```
or use variable `$card-width`

2022-12-04 21:19 UTC, ivanchuk-yurii approved these changes

2023-11-30 10:33 UTC, closed without merging