Develop layout_catalog_grid
mate-academy/layout_catalog_grid pull request #1488
Opened 2023-02-05 23:47 UTC by sergey-lipikhin

- [DEMO LINK](https://sergey-lipikhin.github.io/layout_catalog_grid/)

2023-02-08 13:02 UTC, sergii-nosachenko requested changes

2023-02-08 13:02 UTC, sergii-nosachenko commented on src/styles/_catalog.scss
> +$card-width: 200px;
Create a separate file for variables.

2023-02-08 13:02 UTC, sergii-nosachenko commented on src/styles/_catalog.scss
> +    place-content: center;
🔥

2023-02-08 13:02 UTC, sergii-nosachenko commented on src/styles/_catalog.scss
>    }
You can make a loop to create all media queries. Just create a correctly mapped list to iterate.

2023-02-13 13:24 UTC, Andr1yK approved these changes

2024-03-20 11:19 UTC, closed without merging