reworked  catalog-grid
mate-academy/layout_catalog_grid pull request #1493
Opened 2023-02-06 11:32 UTC by MaksymMaliuk

[DEMO LINK](https://MaksymMaliuk.github.io/layout_catalog_grid/)

2023-02-08 13:07 UTC, sergii-nosachenko requested changes
Add meaningful messages to your commits.

https://initialcommit.com/blog/git-commit-messages-best-practices

2023-02-13 13:25 UTC, Andr1yK approved these changes

2023-02-13 13:25 UTC, Andr1yK commented on src/styles/blocks/_catalog.scss
> +  @include columnTemplates(4, 1024px);
👍

2023-02-13 13:25 UTC, Andr1yK commented on src/styles/utils/_variables.scss
> +);
do u use this variable?

2024-04-21 23:07 UTC, closed without merging