layout catalog grid
mate-academy/layout_catalog_grid pull request #1551
Opened 2023-02-21 23:05 UTC by olyakachmarchyk

https://olyakachmarchyk.github.io/layout_catalog_grid/

2023-02-22 08:35 UTC, tetiana-ivanchenko requested changes

2023-02-22 08:35 UTC, tetiana-ivanchenko commented on src/styles/_catalog.scss
> +    grid-template-columns: repeat(2, 200px);
move width in the variable

2023-02-23 09:03 UTC, tetiana-ivanchenko requested changes

2023-02-23 09:03 UTC, tetiana-ivanchenko commented on src/styles/_catalog.scss
> +    height: $height;
you use it only one time, why do you need variable?

2023-02-23 19:37 UTC, closed without merging

2023-02-24 08:56 UTC, OlEzhA0 requested changes

2023-02-24 08:56 UTC, OlEzhA0 commented on src/styles/_catalog.scss
> +@media (min-width: 488px) {
hey! you can use next syntax
```
.someClass {
  display: grid;

  @media (min-width: 488px) {
    grid-template-columns: repeat(2, $width)
  }

  @media (min-width: 768px) {
    grid-template-columns: repeat(3, $width)
  }
}
```

etc

2023-02-24 20:09 UTC, VitaliyBondarenko1982 approved these changes