flex ot grid
mate-academy/layout_catalog_grid pull request #1585
Opened 2023-03-02 13:41 UTC by Evgenb000

- [DEMO LINK](https://Evgenb000.github.io/layout_catalog_grid/)

2023-03-02 14:15 UTC, BondarenkoDmitriy approved these changes
no comments, good job!

2023-03-03 09:02 UTC, VinnieJ-2k20 requested changes
Layout is broken on ~960 px resolution and below
![image](https://user-images.githubusercontent.com/60885495/222677692-94a24c89-a0d0-4e6f-b608-d5f220a9ee91.png)

2023-03-06 11:17 UTC, Olexandr6 approved these changes
Good job 👍 Make sure to fix comment👇

2023-03-06 11:17 UTC, Olexandr6 commented on src/styles/_catalog.scss
> +    grid-template-columns: repeat(2, 200px);
You used `200px` value in several places, so it makes sense to create a separate variable for it

2023-06-20 13:03 UTC, closed without merging