solution to grid catalog
mate-academy/layout_catalog_grid pull request #183
Opened 2021-11-29 11:43 UTC by mykola-koval

- [DEMO LINK](https://mykola-koval.github.io/layout_catalog_grid/)

2021-11-29 12:09 UTC, Viktor9r requested changes
у тебя при расширении экрана карточки уезжают друг от друга, а нужно, что бы они постоянно были с интервалом 48 пикселей и были сгруппированы в центре
https://prntscr.com/20ymptb

2021-11-29 13:11 UTC, Viktor9r requested changes
у каталога так же должны быть отступы
![image](https://user-images.githubusercontent.com/85190243/143874147-f5969106-d982-404f-8f2f-2363ff7739ae.png)

2021-11-29 13:32 UTC, Viktor9r approved these changes

2021-11-29 13:32 UTC, Viktor9r commented on src/styles/_catalog.scss
>    margin: 0 auto;
я бы поменял на justify-content: center;

2021-12-01 14:38 UTC, Elena-brv approved these changes

2021-12-01 14:38 UTC, Elena-brv commented on src/styles/_catalog.scss
>    }
```suggestion
  @media (min-width: 768px) {
    grid-template-columns: repeat(3, 200px);
  }

  @media (min-width: 1024px) {
    grid-template-columns: repeat(4, 200px);
  }
```

2023-03-02 06:05 UTC, closed without merging