first implementation
mate-academy/layout_catalog_grid pull request #25
Opened 2021-08-29 11:01 UTC by Rocketjet

- [DEMO LINK](https://Rocketjet.github.io/layout_catalog_grid/)

2021-08-29 19:01 UTC, caelum29 requested changes

2021-08-29 19:01 UTC, caelum29 commented on src/styles/_catalog.scss
>      margin-right: 48px;
you don't need these

2021-08-29 19:04 UTC, caelum29 commented
убери лишние марджины

2021-08-29 19:37 UTC, Rocketjet commented
> убери лишние марджины

готово)

2021-08-29 19:37 UTC, caelum29 approved these changes

2021-08-30 09:07 UTC, Ihor-Karpyn approved these changes
Great

2021-08-30 09:07 UTC, Ihor-Karpyn commented on src/styles/_catalog.scss
> +    height: $card-height;
mixin squre

2024-05-29 15:34 UTC, closed without merging