Change flex to grid
mate-academy/layout_catalog_grid pull request #327
Opened 2022-02-23 20:30 UTC by ivan-kadykalo

- [DEMO LINK](https://ivan-kadykalo.github.io/layout_catalog_grid/)

2022-02-24 11:08 UTC, VETALEK approved these changes
All good

2022-02-24 11:08 UTC, VETALEK commented on src/styles/blocks/header.scss
> +  height: $header-hight;
header-hEight

2022-03-08 13:29 UTC, illiarerun requested changes
Nice start, need to fix a few things, tho

2022-03-08 13:29 UTC, illiarerun commented on src/styles/blocks/catalog.scss
> +  @media (min-width: 1190px) {
are you sure it should be 1190? check the task again

2022-03-08 13:29 UTC, illiarerun commented on src/styles/blocks/page.scss
> +  }
```suggestion
    margin-bottom: 50px;
  }
```

2022-03-08 13:29 UTC, illiarerun commented on src/styles/blocks/catalog.scss
> +  @media (min-width: 1190px) {
There should be four columns starting at 1024px
There should be three columns starting at 768px
There should be two columns starting at 488px

2022-03-09 13:20 UTC, illiarerun requested changes

2022-03-09 13:20 UTC, illiarerun commented on src/styles/blocks/catalog.scss
> +  grid-template-columns: repeat(auto-fill, 200px);
use media queries your task still doesn't work properly on resolutions below 1024

2022-03-09 18:34 UTC, illiarerun approved these changes

2023-08-08 17:43 UTC, closed without merging