catalog grid
mate-academy/layout_catalog_grid pull request #350
Opened 2022-03-15 13:05 UTC by plankton9991

- [DEMO LINK](plankton9991.github.io/layout_catalog_grid/)

Додав паддінги щоб було більше простору перед зміною гріда

2022-03-15 15:34 UTC, RuslanaTomnyuk approved these changes
You need to replace `flex` with `grid` as I understood from the instructions, but your card still has flex!

2022-03-15 16:13 UTC, AlinaMatuschak requested changes
fix comment from @RuslanaTomnyuk

2022-03-15 16:39 UTC, AlinaMatuschak requested changes
- from 768px to 1024px should be three columns
<img width="467" alt="Screenshot 2022-03-15 at 18 34 26" src="https://user-images.githubusercontent.com/47606379/158426699-65726d85-a569-4fbd-80f7-650acc8d0b90.png">

- from 488px to 768px should be two columns
<img width="485" alt="Screenshot 2022-03-15 at 18 35 50" src="https://user-images.githubusercontent.com/47606379/158426959-931027ea-f7ea-4c31-8dac-a5c018a7ad2c.png">
<img width="504" alt="Screenshot 2022-03-15 at 18 36 41" src="https://user-images.githubusercontent.com/47606379/158427130-66a0e85f-fba9-4dd0-9149-57bbd7b8a17a.png">

2022-03-15 16:39 UTC, AlinaMatuschak commented on src/styles/_catalog.scss
> +  max-width: 1004px;
Is it necessary?

2022-03-15 16:39 UTC, AlinaMatuschak commented on src/styles/_catalog.scss
> +  padding: 0 30px;
you don't need add paddings

2022-03-15 16:39 UTC, AlinaMatuschak commented on src/styles/_catalog.scss
>      width: 200px;
You set card width on grid-template-columns

2022-03-16 08:09 UTC, AlinaMatuschak approved these changes
Good work 💪

2023-03-10 13:59 UTC, closed without merging