product-grid
mate-academy/layout_catalog_grid pull request #397
Opened 2022-04-02 05:24 UTC by PRO-GRAM-MER

- [DEMO LINK](https://PRO-GRAM-MER.github.io/layout_catalog_grid/)

2022-04-06 10:36 UTC, ihor-jpeg requested changes
Good job! Take a look at my comments

2022-04-06 10:36 UTC, ihor-jpeg commented on src/styles/_catalog.scss
> +  justify-self: center;
what does this do?

2022-04-06 10:36 UTC, ihor-jpeg commented on src/styles/_catalog.scss
> +  "4" 1024px;
where is 1?

2022-04-06 10:36 UTC, ihor-jpeg commented on src/styles/_catalog.scss
>    max-width: 944px;
strange number. maybe calc and variables?

2022-04-06 10:36 UTC, ihor-jpeg commented on src/styles/_catalog.scss
>    margin: 0 auto;
it seems like you are applying margins to a block. that's a no-no

2022-04-25 08:34 UTC, meforoma requested changes

2022-04-25 08:34 UTC, meforoma commented on src/styles/_catalog.scss
>      margin-bottom: 48px;
you have a grid gap already - why duplicate with a margin?
don't

2022-04-26 10:01 UTC, meforoma approved these changes

2026-03-29 20:35 UTC, closed without merging