first commit
mate-academy/layout_catalog_grid pull request #549
Opened 2022-06-07 09:49 UTC by pavel-gutsal

https://pavel-gutsal.github.io/layout_catalog_grid/

2022-06-08 10:53 UTC, ArturErmolenko requested changes

2022-06-08 10:53 UTC, ArturErmolenko commented on src/styles/_catalog.scss
> +  }
use @each something like

```
@each $media-width, $columns in $media {
     @media (min-width:#{$media-width}) {
       grid-template-columns: repeat(#{$columns}, $card-width);
     }
   }
```

2022-06-09 10:52 UTC, pavel-gutsal commented
reported issue in scss with each loop was fixed;

2022-06-10 14:47 UTC, ArturErmolenko approved these changes

2022-10-07 11:10 UTC, closed without merging