grid
mate-academy/layout_catalog_grid pull request #565
Opened 2022-06-13 06:09 UTC by vitalii-labunskyi

- [DEMO LINK](https://vitalii-labunskyi.github.io/layout_catalog_grid/)

2022-06-14 15:14 UTC, Bohdan-Maksymiuk requested changes

2022-06-14 15:14 UTC, Bohdan-Maksymiuk commented on src/styles/_catalog.scss
> +  }
```suggestion
  @media (max-width: 487px) {
    grid-template-columns: repeat(1, 200px);
  }
```

2022-06-14 15:14 UTC, Bohdan-Maksymiuk commented on src/styles/_catalog.scss
> +  }
```suggestion
  @media (max-width: 767px) {
    grid-template-columns: repeat(2 , 200px);
  }
```

2022-06-16 11:56 UTC, vitalii-labunskyi commented
Done!

2022-06-17 12:38 UTC, aliceblunt8 approved these changes

2022-06-17 13:14 UTC, closed without merging