Solution
mate-academy/layout_catalog_grid pull request #58
Opened 2021-09-01 11:07 UTC by anton-kulchytskyi

- [DEMO LINK](https://anton-kulchytskyi.github.io/layout_catalog_grid/)

2021-09-02 18:39 UTC, vkryvytskyy reviewed
![image](https://user-images.githubusercontent.com/38065883/131898689-2f5684b8-5b9a-4728-9128-aa9672180acb.png)
Кажется блок с карточками должен быть по центру

2021-09-02 18:40 UTC, vkryvytskyy requested changes

2021-09-02 18:40 UTC, vkryvytskyy commented on src/index.html
> +            <div class="stars">
Тут должен быть модификатор `stars--4`, именно он отвечает за количество активных звездочек

2021-09-02 18:40 UTC, vkryvytskyy commented on src/styles/_catalog.scss
> +  transition: all linear 0.3s;
Не используй all, укажи какие именно свойства анимируются(color, transform)

2021-09-03 08:25 UTC, anton-kulchytskyi commented on src/styles/_catalog.scss
> +  transition: all linear 0.3s;
Зміни додано; я зрозумів, що завдання було залишити блок зліва....
![grid](https://user-images.githubusercontent.com/61460228/131974702-5b994bee-c722-4ddd-ab67-186d3369e63b.png)

2021-09-06 09:38 UTC, vkryvytskyy reviewed
![image](https://user-images.githubusercontent.com/38065883/132195858-2933eda8-6745-4e3f-91b5-b16727ded037.png)
У меня на большом экране блок сейчас не по центру, сделай так, чтобы он был по центур

2021-09-09 13:49 UTC, mykola-yarchuk approved these changes

2021-09-21 13:31 UTC, closed without merging