Develop
mate-academy/layout_catalog_grid pull request #621
Opened 2022-06-20 15:43 UTC by Glebatikot

- [DEMO LINK](https://Glebatikot.github.io/layout_catalog_grid/)

2022-06-20 15:48 UTC, budanov20 commented
добре

2022-06-21 06:50 UTC, VETALEK requested changes
Nice 👌

2022-06-21 06:50 UTC, VETALEK commented on src/styles/_catalog.scss
> +  grid-template-columns: repeat(auto-fill, 200px);
this rule never works, cause you covered all the scenarios with media queries 😭

2022-06-21 06:50 UTC, VETALEK commented on src/styles/_catalog.scss
> +  grid-template-columns: repeat(auto-fill, 200px);
so you don't need it

2022-06-21 07:07 UTC, VETALEK approved these changes
🔥

2022-06-30 07:18 UTC, closed without merging