grid catalog
mate-academy/layout_catalog_grid pull request #651
Opened 2022-07-07 20:17 UTC by p-omogit-e

- [DEMO LINK](https://p-omogit-e.github.io/layout_catalog_grid/)

2022-07-12 09:35 UTC, Bohdan-Maksymiuk requested changes

2022-07-12 09:35 UTC, Bohdan-Maksymiuk commented on src/styles/_catalog.scss
> +    max-width: 4 * $cardWidth + 3 * $cardGap;
you don't need max-width here
just use power of the grid)
```suggestion
    grid-template-columns: repeat(4, $cardWidth);
```

2022-07-12 09:36 UTC, Bohdan-Maksymiuk commented on src/styles/_catalog.scss
> +    max-width: 4 * $cardWidth + 3 * $cardGap;
fix in other places

2022-07-19 12:59 UTC, ArturErmolenko approved these changes

2025-12-17 21:20 UTC, closed without merging