changed flex to grid
mate-academy/layout_catalog_grid pull request #73
Opened 2021-09-20 10:46 UTC by cyb1ove

- [DEMO LINK](https://cyb1ove.github.io/layout_catalog_grid/)

2021-09-20 11:10 UTC, MariiaObraztsova requested changes
1. Собери все изменения в одном месте: либо в main, либо в catalog.
2. Добавь расположение для экранов < 488px

2021-09-20 11:10 UTC, MariiaObraztsova commented on src/styles/_catalog.scss
> +  @media (min-width: 488px) {
У тебя нет варианта на экраны до 488px, там должна одна карточка помещаться. Его стоит прописать как первоначальный в каталоге

2021-09-20 11:10 UTC, MariiaObraztsova commented on src/styles/main.scss
> +  grid-template-columns: repeat(4, $card_width);
ты это уже прописал в файле каталога, как и медиа-запросы ниже. Собери это все в одном месте :)

2021-09-20 11:25 UTC, MariiaObraztsova approved these changes
Awesome

2021-09-21 13:20 UTC, VinnieJ-2k20 approved these changes
Good job 👍

2021-09-21 13:20 UTC, VinnieJ-2k20 commented on readme.md
> +- Do not modify headerdf.gmlcdvgmldfgmld
???

2025-01-20 16:42 UTC, closed without merging