Create catalog with grid
mate-academy/layout_catalog_grid pull request #818
Opened 2022-08-23 15:17 UTC by Vladosik1337

- [DEMO LINK](https://Vladosik1337.github.io/layout_catalog_grid/)

2022-08-25 15:47 UTC, dmytristepanov requested changes
your link is not working :(

2022-08-25 15:47 UTC, dmytristepanov commented on src/styles/blocks/_catalog.scss
> +  margin: 0 auto;
I think you don't need these properties when you are using grids.

2022-08-25 15:47 UTC, dmytristepanov commented on src/index.html
> +            <a href="#" class="nav__link">Samsung</a>
Let's specify some anchor link in all cases instead of using a single # sign

2022-08-26 04:05 UTC, dmytristepanov approved these changes
Great work!

2022-09-01 05:02 UTC, Andr1yK approved these changes

2025-11-08 12:43 UTC, closed without merging