flex replaced with grid
mate-academy/layout_catalog_grid pull request #892
Opened 2022-08-30 15:25 UTC by roman-zherebetskyi

[DEMO LINK](https://roman-zherebetskyi.github.io/layout_catalog_grid/)

2022-08-30 16:00 UTC, Oleksandra-Shevchenko approved these changes

2022-08-30 17:32 UTC, roman-zherebetskyi commented on src/styles/_mediaQs.scss
> +}
yeah I know, I just wanted to separate it and try if it will work like this

2022-08-30 17:32 UTC, roman-zherebetskyi commented on src/styles/_catalog.scss
> +    display: grid;
ow, I didn't know that, but okay let it be...

2022-08-30 17:32 UTC, roman-zherebetskyi commented on src/styles/_mediaQs.scss
> +}
thanks for the review

2022-08-31 05:53 UTC, MaksimusCRS requested changes

2022-08-31 05:53 UTC, MaksimusCRS commented on src/styles/_mediaQs.scss
> +}
@roman-zherebetskyi it's a wrong way actually, let's add only needed property to media queries

2022-08-31 09:18 UTC, roman-zherebetskyi commented on src/styles/_mediaQs.scss
> +}
okay I understood, fixed!

2022-09-02 06:37 UTC, MaksimusCRS approved these changes
GJ

2024-01-20 10:25 UTC, closed without merging